# Parameters for rosbag processing (data read/write from/to rosbag)
rosbag:
  write_out:
    enable: true
    filename: "aloam_out.bag"
    input_points: false
    pointclouds: false
  shutdown_ros: true
